name: Test and deploy
run-name: ${{ github.actor }} runs test and deploy
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
         cd /var/www/
         git init
         eval "$(ssh-agent -s)"
         ssh-add ~/.ssh/winc
         ssh -T git@github.com
         git pull git@github.com:dgdck/CD-project.git main
         cp /var/www/main.py /var/www/foo
         systemctl restart nginx
